server:
  port: 9527

spring:
  application:
    name: cloud-zuul-gateway

zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  host:
    connect-timeout-millis: 60000 # HTTP??????Hystrix?????
    socket-timeout-millis: 60000 # socket??9527

eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      defaultZone: http://10.176.22.104:8716/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true